<a href="https://colab.research.google.com/github/farhanfaiyazkhan/tensor-flow-ml/blob/main/Tensor_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is a Tensor?
 A tensor is a generalization of vectors and matrices to potentially higher dimensions.

In [9]:
import tensorflow as tf

In [10]:
string_tf = tf.Variable("this is a tensor string", tf.string)
int_tf = tf.Variable(23, tf.int16)
float_tf = tf.Variable(3.145, tf.float64)

# Rank
A rank or degree is dimension of a tensor variable.

In [11]:
tf.rank(string_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [16]:
rank1 = tf.Variable(["hello", "hey", "hi"], tf.string)
rank2 = tf.Variable([[1, 2, 3], [3, 4, 5], [5, 5, 5]], tf.int16) # matrix

In [17]:
tf.rank(rank1)
tf.rank(rank2)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

# Shape
Shape is how many elements each dimension contains.

In [38]:
rank1.shape

TensorShape([3])

In [39]:
rank2.shape

TensorShape([3, 3])

In [44]:
string_tf.shape

TensorShape([])

In [46]:
tensor1 = tf.ones([1, 2, 3])

In [47]:
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [48]:
tensor2 = tf.reshape(tensor1, [2, 3, 1])

In [49]:
print(tensor2)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [51]:
tensor3 = tf.reshape(tensor2, [6])

In [52]:
print(tensor3)

tf.Tensor([1. 1. 1. 1. 1. 1.], shape=(6,), dtype=float32)


In [53]:
tensor4 = tf.reshape(tensor1, [3, -1])

In [54]:
print(tensor4)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


# Types of Tensors



1.   Variable
2.   Constant
3.   Placeholder
4.   SparseTensor

Only Variable is mutable out of these.